### PR TITLE
feat(gui): workspace switcher UI — list/create/rename/delete/switch (sq-lmlch)

### PR DESCRIPTION
**Pull request by jeswr**
## Summary

> �� SPARQ agent — implementing bead sq-lmlch (workspace switcher UI in the left rail).

- **`workspace-switcher.tsx`** (new): Radix Popover listing all `WorkspaceSummary` rows with switch-on-click, inline rename (Enter to save / Esc to cancel), inline confirm-delete (cannot crash on last-workspace delete — context handles fallback), and "New workspace" name prompt. Shows honest backend label ("saved on device" / "in this browser" / "this session only") in the popover header.
- **`left-rail.tsx`**: replaces the dead stub button (`title="persistent workspaces are a later phase"`) with `<WorkspaceSwitcher />`. Adds import; removes unused `ChevronDown`/`Circle` icons from the stub.
- **`workspace-switcher.spec.ts`** (new): 7 Playwright tests covering trigger rendering, backend label, create→distinct-data→switch-preserves-each (non-vacuous: ASK queries against live engine per workspace), rename reflected in trigger, delete non-active safe, delete active falls back to another workspace, Cmd-K "New workspace" wires up.
- **Cmd-K commands** registered via `useRegisterPaletteCommands("workspace", ...)`: "New workspace", "Switch workspace…", and per-workspace "Switch to `<name>`" rows for every non-active workspace.

## Invariants preserved

- The UI NEVER calls `hydrateFromSnapshot` directly — all lifecycle goes through `switchWorkspace` / `createWorkspace` / `renameWorkspace` / `deleteWorkspace` (sq-lcd6e). Save-current-snapshot before switching is owned by the context.
- Deleting the active workspace is handled by the context (switches to most-recently-updated, or creates a fresh default). UI confirms inline but does not implement fallback logic.
- Data-driven rail structure (sq-1odi9) is untouched — the switcher only touches the `border-b px-2 py-2` header div.
- Does NOT touch inference-control files (sq-glo5r concurrency constraint).

## Gates

- `npm run build:web` ✅
- `npm run build:tauri` ✅  
- `npx tsc --noEmit` ✅
- `next lint` ✅
- Playwright chromium-mock-ipc: 35/35 ✅ (all passing)
- Playwright chromium-web: 9/10 (1 pre-existing failure: `streaming-tool.web.spec.ts` needs the RSP WASM bundle built separately — fails on main HEAD too, from #1529)

## Test plan

- [ ] Open the app; workspace trigger shows active workspace name + green LED
- [ ] Click trigger → popover lists workspaces with backend label  
- [ ] Click "New workspace" → inline input → type name → Enter → workspace created, active
- [ ] Rename a workspace → name updates in trigger and popover list
- [ ] Delete a non-active workspace → row disappears, active workspace unchanged
- [ ] Delete the active workspace → app switches to fallback without crashing
- [ ] Cmd-K → "New workspace" → popover opens in create mode

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jeswr** [comment]
🤖 SPARQ agent — mechanical-verify PASS + ARM.

**Checklist:**
- ✅ **gates_both_feature_states**: ci-summary SUCCESS; gate (8m31s) completed with all required checks SUCCESS or SKIPPED; GUI Playwright mocked-IPC lane 35/35 PASS.
- ✅ **tests_non_vacuous**: 'create workspace B → distinct data in each workspace → switch preserves each' uses real SPARQL ASK queries against live engine per workspace — assertions on true/false results would fail if switchWorkspace/createWorkspace didn't preserve snapshots.
- ✅ **opt_in_feature_discipline**: NA (TypeScript/GUI only, no Rust cargo features).
- ✅ **readme_skill_synced**: NA (no new Rust public API surface; GUI component implementation).
- ✅ **no_hardcoded_perf_md**: no baked perf numbers in any markdown hunks.
- ✅ **coverage_floor_not_regressed**: NA (TypeScript/GUI only, no Rust coverage impact).

**Surface:** GUI frontend component (workspace-switcher.tsx) integrating sq-lcd6e context APIs. No judgment surfaces — straightforward UI implementation, no ZK/MPC/security, honest backend labels present, invariants documented and preserved (never calls hydrateFromSnapshot directly).

**Result:** ARM — PR already queued to merge via `--squash --auto`. PR mergeStateStatus=UNSTABLE is expected (async code_quality ruleset eval; self-resolves ~11min per merge mechanics).

[OPUS-4.8]
